services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Expose port 80
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the custom nginx configuration
    depends_on:
      - contas  # Ensure contas service starts before nginx
    networks:
      - DB_to_contas
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${PSSWD}
      POSTGRES_DB: contas
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - DB_to_contas
  contas:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 5
    environment:
      POSTGRES_DB_URL: jdbc:postgresql://db:5432/contas?user=user&password=${PSSWD}
    networks:
      - DB_to_contas
    ports:
      - "8080"
    depends_on:
      - db

networks:
  DB_to_contas:
    driver: bridge